<div id="textos1">
<h2>Databases</h2><br/>

<p>During the first and second votes of the Presidential election, the NeoFluxo system collected data from official sources and specific terms on Twitter. These were organized in different databases, all accessible through an API, which allows any developer to create and visualize possible relationships between them.</p><br/><br/>

<h4 id="tt">Data collected from the Official Channels:</h4><br/>

<ul>
<li>- All updates from the official channels of candidates Dilma Rouseff and Jose Serra on the Internet, from Twitter, Facebook, YouTube, Flickr and the official websites (no filter):</li><br/>
		<ul>
		   <li>:: First vote: between 09/11/2010 and 10/03/2010</li>
		   <li>:: Second vote: between 10/08/2010 and 10/29/2010</li>
		</ul>
<br/>	
<li>- All updates from the official channels of candidate Marina Silva on the Internet, from Twitter, Facebook, YouTube, Flickr and the official website (no filter);</li><br/>
	<ul>
		<li>:: First vote: between 09/23/2010 and 10/03/2010</li>
	</ul>
</ul>
<br/>
<br/>
<hr/>
<br/>
<br/>


<h4 id="tt">Data collected only on Twitter:</h4><br/>

<ul>
<li>- All messages on Twitter containing the words "Dilma" and "Serra" (separate tables).</li><br/>
	<ul>
		<li>:: First vote: between 09/11/2010 and 10/03/2010</li>
		<li>:: Second vote: between 10/08/2010 and 10/29/2010</li>
	</ul>
<br/>	
<li>- All messages on Twitter containing one or more of the keywords (automatically generated) from official channels of candidates Dilma Rousseff and Jose Serra. The tables, separated for each candidate, contain sub-tables divided by day (the same day of the TV shows), where each of these sub-tables has 10 (ten) related keywords.</li><br/>
	<ul>
		<li>:: First vote: between 09/11/2010 and 10/03/2010</li>
		<li>:: Second vote: between 10/08/2010 and 10/29/2010</li>
	</ul>
<br/>	
<li>- All messages on Twitter containing one or more of the keywords (automatically generated) from official channels of candidate Marina Silva. The tables contain sub-tables divided by day (the same day of the TV shows), where each of these sub-tables has 10 (ten) related keywords.</li><br/>
	<ul>
		<li>:: First vote: between 09/23/2010 and 10/03/2010</li>
	</ul>
<br/>	
<li>- All messages on Twitter containing one or more keywords (generated manually by the researchers based on the TV shows) from candidates Dilma Roussef and Jose Serra. The tables, separated by candidate, contain sub-tables divided by day (created after each broadcast), where each of these sub-tables has 10 (ten) related keywords according to a previously defined methodology.</li><br/>
	<ul>
<li>:: First vote: between 09/11/2010 and 10/03/2010</li>
<li>:: Second vote: between 10/08/2010 and 10/29/2010</li>
	</ul>
<br/>	
<li>- All messages on Twitter containing one or more keywords (generated manually by the researchers based on the TV programs) from candidate Marina Silva. The table contain sub-tables divided by day (created after each broadcast), where each of these sub-tables has 10 (ten) related keywords according to a previously defined methodology.</li><br/>
	<ul>
		<li>:: First vote: 09/23/2010 and 10/03/2010</li>
	</ul>
<br/>
<li>- All messages on Twitter, containing one or more keywords (manually generated by the researchers) from issues related to the coverage of the election campaign by the four major Brazilian Web portals (UOL, Terra, iG and G1), with a limit of 5 (five) terms every day, according to a previously defined methodology.</li><br/>
	<ul>
		<li>:: Second vote: between 10/08/2010 and 10/29/2010</li>
	</ul>
<br/>

	
</ul>
</div>










